version: '3.9'
services:
  notebook:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - FTP_PROXY=$FTP_PROXY
        - ftp_proxy=$ftp_proxy
        - NO_PROXY=$NO_PROXY
        - no_proxy=$no_proxy

    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - http_proxy=$http_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
      - https_proxy=$https_proxy
      - FTP_PROXY=$FTP_PROXY
      - ftp_proxy=$ftp_proxy
      - NO_PROXY=$NO_PROXY
      - no_proxy=$no_proxy
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"

    volumes:
      - ./work:/home/work
    expose:
      - "8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
